### ISSUE TITLE
Issues with iOS Installation + NPM install link?

### ISSUE THREAD

**Issue by sean-perkins** [mobilemindtec/nativescript-background-task#7] opened 2017-11-29 06:12 UTC
First off this looks like a very promising plugin for the NativeScript community! Great work so far!

There's a few things that would be great to resolve, to make it usable in external projects. 
1. The only way to install this plugin is to clone it, manually `npm pack` it and then install it. It would great if you published this to `npm`. 
2. There appears to be an issue with referencing the cocoapod from your github account. It would be great if you published the underlying library to Cocoapods, so you could install it via `pod install 'NSBackgroundTask'`.

The error I specifically get when trying to install the pod is:
```
Installing pods...
Analyzing dependencies
Pre-downloading: `NSBackgroundTask` from `git@github.com:mobilemindtec/nativescript-background-task-ios-source.git`

[!] Error installing NSBackgroundTask
[!] Failed to download 'NSBackgroundTask'.
```

When I tried to fix the pod locally, it looks like the UIKit framework is missing from a header reference somewhere.

**Comment by mobilemindtec** [comment] 2017-11-29 16:22
Hi, 

Thank you for reporting the problem!

To fix, change on plugin's Podefile `git@github.com:mobilemindtec` to `https://github.com/mobilemindtec`. `git@github` require authentication and this must be the problem. The problem is already fixed on plugin source code.

You can use github repo directly on your package.json, don't need pack plugin:

```
"nativescript-background-task": "https://github.com/mobilemindtec/nativescript-background-task.git"
```

**Closed** 2017-12-20 02:05 UTC
